# Generated by Django 3.1.6 on 2023-06-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LargeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=50)),
                ('banner_image', models.ImageField(upload_to='large_banner/images')),
                ('banner_description', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
