# Generated by Django 3.1.6 on 2023-06-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('large_banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='largebanner',
            old_name='banner_image',
            new_name='image',
        ),
    ]
