# Generated by Django 3.1.6 on 2023-06-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('large_banner', '0002_auto_20230617_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='largebanner',
            name='contactNumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='largebanner',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
